"""back populates fix

Revision ID: 2608f6eddfb8
Revises: 1b970771d0eb
Create Date: 2022-04-04 14:16:38.482221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2608f6eddfb8'
down_revision = '1b970771d0eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
