"""delete is_superuser field

Revision ID: 262cbbc45a98
Revises: adf1d6be83ae
Create Date: 2022-04-06 14:18:25.514398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '262cbbc45a98'
down_revision = 'adf1d6be83ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
